---
title: "PICRUSt2"
author: "Heather Deel"
date: "2023-10-20"
output: html_document
---

### Getting PICRUSt2 functions for Density/Diversity analysis

### Setup and libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(emmeans)
library(ggplot2)
library(ggthemes)
library(multcomp)
library(phyloseq)
library(RColorBrewer)
library(readxl)
library(tidyverse)
library(microbiomeMarker)
```

```{r setup, echo=FALSE}
source("myFunctions.R")
```

### Convert taxa Relative Abundances to PICRUSt2 GIBBs Relative Abundances
```{r}
# Create GIBBs relative abundances for RhizoDD1
EC.gibbs.info <- read.csv('GIBBs.EC.numbers.csv')
EC.gibbs <- read.csv('EMU_database.GIBBs.EC.PICRUSt2.R.csv')

row.names(EC.gibbs) <- EC.gibbs$tax_id
EC.gibbs <- EC.gibbs[,2:34]

df <- read.csv('../rel_abund_16S_ABC_qpcr_adj.csv')

EC.sub <- EC.gibbs
EC.bin <- EC.sub %>% 
  mutate_if(is.numeric, ~1 * (. > 0))

samples <- names(df)[9:length(names(df))]
enzymes <- names(EC.sub)[11:length(names(EC.sub))]
reads <- colSums(df[,samples], na.rm=T)

final <- data.frame(matrix(ncol = length(samples), nrow = length(enzymes)))
names(final) <- samples
row.names(final) <- enzymes
i = samples[2]
for (i in samples) {
  for (j in enzymes) {
    value <- sum(df[,i] / EC.bin$X16S_rRNA_Count * EC.bin[,j], na.rm=T) / reads[i]
    final[j,i] <- value
  }
}
write.csv(final, 'GIBBs.rel_abund.final.A.csv')
```